[PIL-732][AV] - RFM Contact Name and Guidance Page
hmrc/pillar2-frontend pull request #218
Opened 2024-02-29 10:04 UTC by aashik-varahan

2024-03-01 09:52 UTC, alikouhestani requested changes

2024-03-01 09:52 UTC, alikouhestani commented on app/cache/SessionData.scala
> +  def corporatePosition(value: String)(implicit request: Request[AnyContent]): Session =
We no longer store data on Session. You need to store any non-authenticated journey data on sessionRepository

2024-03-01 09:52 UTC, alikouhestani commented on app/controllers/rfm/CorporatePositionController.scala
> +              .withSession((sessionData.corporatePosition(value.toString)))
again, please refrain from storing data on session as this data is public across HMRC and its frowned upon to store data like this

2024-03-01 11:14 UTC, alikouhestani approved these changes

2024-03-14 11:41 UTC, alikouhestani requested changes

2024-03-14 11:41 UTC, alikouhestani commented on app/controllers/rfm/UpeStartPageRegistrationController.scala
> +  view:                     UpeStartPageRegistrationView
Is the naming correct for this one? Why is it called a "Upe" (Ultimate Parent Entity) if this a part of the RFM (Replace Filing Member) Journey

2024-03-14 11:41 UTC, alikouhestani commented on app/forms/RfmUpeNameRegistrationFormProvider.scala
> +
again, is the naming right?

2024-03-14 11:41 UTC, alikouhestani commented on app/pages/rfmUpeNameRegistrationPage.scala
> +import play.api.libs.json.JsPath
see above

2024-03-14 11:41 UTC, alikouhestani commented on app/views/rfm/UpeNameRegistrationView.scala.html
> +
see above

2024-03-14 11:41 UTC, alikouhestani commented on app/views/rfm/UpeStartPageRegistrationView.scala.html
> +@this(
see above

2024-03-14 11:41 UTC, alikouhestani commented on test/controllers/rfm/CorporatePositionControllerSpec.scala
>          .overrides(
.configure(
          Seq(
            "features.rfmAccessEnabled" -> true
          ): _*
        )
        why do we need this if the toggle is set to true in local anyway?

2024-03-14 11:41 UTC, alikouhestani commented on test/controllers/rfm/UpeNameRegistrationControllerSpec.scala
> +class UpeNameRegistrationControllerSpec extends SpecBase {
Same issue with the naming convention

2024-03-14 11:41 UTC, alikouhestani commented on test/controllers/rfm/UpeNameRegistrationControllerSpec.scala
> +            "features.rfmAccessEnabled" -> true
again this toggle is set to true in local so this is redundant

2024-03-14 11:41 UTC, alikouhestani commented on test/controllers/rfm/UpeNameRegistrationControllerSpec.scala
> +            "features.rfmAccessEnabled" -> false
see above

2024-03-14 11:41 UTC, alikouhestani commented on test/controllers/rfm/UpeNameRegistrationControllerSpec.scala
> +            "features.rfmAccessEnabled" -> true
see above

2024-03-14 11:41 UTC, alikouhestani commented on test/controllers/rfm/UpeNameRegistrationControllerSpec.scala
> +            "features.rfmAccessEnabled" -> true
see above

2024-03-14 11:41 UTC, alikouhestani commented on test/controllers/rfm/UpeNameRegistrationControllerSpec.scala
> +            "features.rfmAccessEnabled" -> true
see above

2024-03-14 12:11 UTC, aashik-varahan commented on app/controllers/rfm/UpeStartPageRegistrationController.scala
> +  view:                     UpeStartPageRegistrationView
@alikouhestani - As previously mentioned in other tickets, following FM validation, the UPE can assume the NFM role, or a completely new NFM entity can replace the existing one. This ticket pertains to selecting the UPE radio button as part of PIL-715.

We may need a broader discussion to determine naming conventions, but I presume it aligns with the UPE and NFM journey in Reg and Sub.

2024-03-14 12:12 UTC, aashik-varahan commented on app/forms/RfmUpeNameRegistrationFormProvider.scala
> +
Check reply above.

2024-03-14 12:12 UTC, aashik-varahan commented on app/pages/rfmUpeNameRegistrationPage.scala
> +import play.api.libs.json.JsPath
Check reply above.

2024-03-14 12:12 UTC, aashik-varahan commented on test/controllers/rfm/UpeNameRegistrationControllerSpec.scala
> +            "features.rfmAccessEnabled" -> false
Redundant code for toggle config is now removed.

2024-03-14 12:12 UTC, aashik-varahan commented on test/controllers/rfm/UpeNameRegistrationControllerSpec.scala
> +            "features.rfmAccessEnabled" -> true
Redundant code for toggle config is now removed.

2024-03-14 12:20 UTC, alikouhestani commented on app/controllers/rfm/UpeStartPageRegistrationController.scala
> +  view:                     UpeStartPageRegistrationView
@aashik-varahan 
They can end up on this start page whether if they are a new fm replacing the old one or an existing upe (feel free to check the Mural). Therefore, calling it "UpeStartPageRegistration" indicates that this journey is somehow related to the Ultimate parent which is not.

2024-03-14 14:13 UTC, aashik-varahan commented on app/controllers/rfm/UpeStartPageRegistrationController.scala
> +  view:                     UpeStartPageRegistrationView
@alikouhestani - Renamed the controller class now. It is discussed with @AKKUM that we will follow adding a Prefix 'Rfm' to the name of the files within RFM journey going forward.

2024-03-14 16:40 UTC, alikouhestani approved these changes

2024-03-14 17:23 UTC, merged