[PIL-739][AV] - RFM Capture Name and Address of New NFM
hmrc/pillar2-frontend pull request #224
Opened 2024-03-08 09:15 UTC by aashik-varahan

2024-03-08 10:41 UTC, jassalrichy commented on app/controllers/rfm/NfmNameRegistrationController.scala
> +/*
can we rename this contoller to '**NameRegistrationController'** as it is within rfm package.

2024-03-08 10:43 UTC, jassalrichy commented on app/controllers/rfm/NfmRegisteredAddressController.scala
> +/*
can we rename this contoller to '**RegisteredAddressController**' as it is within rfm package.

2024-03-08 10:44 UTC, jassalrichy commented on app/forms/RfmNfmNameRegistrationFormProvider.scala
> +/*
can we rename this form to '**RfmNameRegistrationFormProvider**'.

2024-03-08 10:45 UTC, jassalrichy commented on app/forms/RfmNfmRegisteredAddressFormProvider.scala
> +/*
can we rename this form to '**RfmRegisteredAddressFormProvider**'.

2024-03-08 10:46 UTC, jassalrichy commented on app/pages/rfmNfmNameRegistrationPage.scala
> +/*
Can we rename this page to '**rfmNameRegistrationPage**'

2024-03-08 10:47 UTC, jassalrichy commented on app/pages/rfmNfmRegisteredAddressPage.scala
> +/*
Can we rename this page to '**rfmRegisteredAddressPage**'

2024-03-08 10:48 UTC, alikouhestani commented on app/pages/rfmNfmNameRegistrationPage.scala
> +/*
Actually can we use '**RfmNameRegistrationPage**' as its an object
@jassalrichy  @aashik-varahan

2024-03-08 10:49 UTC, alikouhestani commented on app/pages/rfmNfmRegisteredAddressPage.scala
> +/*
Again can we please use upper camel case (see above)

2024-03-08 10:50 UTC, jassalrichy commented on app/views/rfm/NfmNameRegistrationView.scala.html
> +@*
Can we rename this view as '**NameRegistrationView**' as it is within rfm subfolder.

2024-03-08 10:50 UTC, jassalrichy commented on app/views/rfm/NfmRegisteredAddressView.scala.html
> +@*
Can we rename this view as '**RegisteredAddressView**' as it is within rfm subfolder.

2024-03-08 10:53 UTC, jassalrichy commented on conf/messages.en
> +rfm.nfmNameRegistration.title = What is the name of the new nominated filing member?
Ideally remove the (nfm) from the message keys. for example:
'rfm.**nfm**NameRegistration.heading' to 'rfm.NameRegistration.heading'

2024-03-08 10:54 UTC, jassalrichy commented on test/controllers/rfm/NfmNameRegistrationControllerSpec.scala
> +/*
can we rename this contoller spec to '**NameRegistrationControllerSpec**' as it is within rfm package.

2024-03-08 10:55 UTC, jassalrichy commented on test/controllers/rfm/NfmRegisteredAddressControllerSpec.scala
> +/*
can we rename this contoller spec to '**RegisteredAddressControllerSpec**' as it is within rfm package.

2024-03-08 10:57 UTC, jassalrichy commented on app/controllers/rfm/NfmNameRegistrationController.scala
> +  val form = formProvider()
Add type annotation:
val form: **Form[String]** = formProvider()

2024-03-08 12:01 UTC, aashik-varahan commented on app/controllers/rfm/NfmNameRegistrationController.scala
> +/*
@jassalrichy - The prefix **'Nfm'** was introduced to distinguish between the UPE and the New NFM within RFM. This was necessary because the UPE journey shares the same set of pages and names (refer PIL-732), such as NameRegistrationController and AddressRegistrationController within RFM.

2024-03-08 12:02 UTC, aashik-varahan commented on app/controllers/rfm/NfmRegisteredAddressController.scala
> +/*
Same as stated above
The prefix **'Nfm'** was introduced to distinguish between the UPE and the New NFM within RFM. This was necessary because the UPE journey shares the same set of pages and names (refer PIL-732), such as NameRegistrationController and AddressRegistrationController within RFM.

2024-03-08 12:02 UTC, aashik-varahan commented on app/forms/RfmNfmRegisteredAddressFormProvider.scala
> +/*
Same as commented above

2024-03-08 12:03 UTC, aashik-varahan commented on conf/messages.en
> +rfm.nfmNameRegistration.title = What is the name of the new nominated filing member?
Same reason as commented above

2024-03-08 12:03 UTC, aashik-varahan commented on test/controllers/rfm/NfmNameRegistrationControllerSpec.scala
> +/*
Same as commented above

2024-03-08 12:05 UTC, aashik-varahan commented on app/pages/rfmNfmNameRegistrationPage.scala
> +/*
@alikouhestani - Agree to use Upper Came Case for Objects, but that should be implemented across all other Object names to maintain consistency.

2024-03-08 12:12 UTC, aashik-varahan commented on test/controllers/rfm/NfmRegisteredAddressControllerSpec.scala
> +/*
Same as commented above

2024-03-08 12:19 UTC, aashik-varahan commented on app/controllers/rfm/NfmNameRegistrationController.scala
> +  val form = formProvider()
@jassalrichy - Updated the changes

2024-03-08 12:34 UTC, jassalrichy commented on test/controllers/rfm/NfmRegisteredAddressControllerSpec.scala
> +    "must return OK and the correct view for a GET if RFM access is enabled and no previous data is found" in {
Need a test for when data was previously entered.

2024-03-08 12:42 UTC, jassalrichy commented on app/controllers/rfm/NfmRegisteredAddressController.scala
> +        .getOrElse(Redirect(controllers.routes.UnderConstructionController.onPageLoad))
Should redirect to JourneyRecovery if previous question, for Name, is not answered.

2024-03-08 12:48 UTC, jassalrichy commented on app/controllers/rfm/NfmRegisteredAddressController.scala
> +      .getOrElse(Future.successful(Redirect(controllers.routes.UnderConstructionController.onPageLoad)))
redirected to journey recovery if previous question, for Name, is not answered for this POST

2024-03-08 12:54 UTC, jassalrichy commented on test/controllers/rfm/NfmRegisteredAddressControllerSpec.scala
> +        .configure(
override of feature toggle not required when testing onSubmit method.

2024-03-08 13:00 UTC, alikouhestani commented on app/controllers/rfm/NfmNameRegistrationController.scala
> +/*
but we already have NfmNameRegistrationController @aashik-varahan given that this is entirely a separate journey. Why are we using the same name for it?

2024-03-08 16:49 UTC, aashik-varahan commented on test/controllers/rfm/NfmRegisteredAddressControllerSpec.scala
> +    "must return OK and the correct view for a GET if RFM access is enabled and no previous data is found" in {
Added a test to cover this scenario

2024-03-08 16:49 UTC, aashik-varahan commented on app/controllers/rfm/NfmRegisteredAddressController.scala
> +        .getOrElse(Redirect(controllers.routes.UnderConstructionController.onPageLoad))
Routed to JourneyRecoveryController class

2024-03-08 16:50 UTC, aashik-varahan commented on app/controllers/rfm/NfmRegisteredAddressController.scala
> +      .getOrElse(Future.successful(Redirect(controllers.routes.UnderConstructionController.onPageLoad)))
Routed to JourneyRecoveryController class

2024-03-08 16:50 UTC, aashik-varahan commented on test/controllers/rfm/NfmRegisteredAddressControllerSpec.scala
> +
Added a unit test to cover this scenario

2024-03-08 16:50 UTC, aashik-varahan commented on test/controllers/rfm/NfmRegisteredAddressControllerSpec.scala
> +        .configure(
Removed the unwanted overrides

2024-03-08 16:51 UTC, aashik-varahan commented on test/controllers/rfm/NfmRegisteredAddressControllerSpec.scala
> +      val application = applicationBuilder(userAnswers = None)
Added NameRegistration value in UserAnswers

2024-03-08 16:56 UTC, aashik-varahan commented on app/controllers/rfm/NfmNameRegistrationController.scala
> +/*
@alikouhestani - As I mentioned earlier, we have separate NameRegistrationController classes for UPE and New NFM within the RFM journey. The prefixes 'Nfm' and 'Upe' help distinguish these classes.

You pointed out the NfmRegisteredAddressController class in the fm directory, but this class resides in the rfm directory. Both classes have **identical page structures and functions**, differing only in the journey they serve. By naming them as fm.NfmRegisteredAddressController and rfm.NfmRegisteredAddressController, we can easily differentiate them while maintaining consistency.

While adding another prefix like RFM to the class file name could improve clarity, removing the prefix NFM from the class name is generally not recommended as it may cause confusion. Additionally, we already have another class rfm/UpeNameRegistrationController.scala, so generalizing it is not feasible.

2024-03-08 17:01 UTC, aashik-varahan commented on app/controllers/rfm/NfmNameRegistrationController.scala
> +/*
I also believe it would be beneficial to have a discussion about naming conventions with all the developers. This way, we can ensure consistency across the entire repository.
@jassalrichy @AKKUM

2024-03-10 20:11 UTC, jassalrichy commented on test/controllers/rfm/NfmRegisteredAddressControllerSpec.scala
> +            ("addressLine1", "27 house"),
The controller attempts to read the address from userAnswers. If Some(value) is returned then the address fields are populated. You need to setup userAnswers rfmNfmRegisteredAddressPage with a valid address to test this senario.

2024-03-10 20:19 UTC, jassalrichy commented on test/controllers/rfm/NfmRegisteredAddressControllerSpec.scala
>      "must redirect to the UnderConstructionController page when valid data is submitted" in {
Need a test that checks redirect to JourneyRecovery if previous question, for Name, is not answered, for the form submission.

2024-03-10 20:20 UTC, jassalrichy commented on test/controllers/rfm/NfmRegisteredAddressControllerSpec.scala
> +    "must return OK and the correct view for a GET if RFM access is enabled and no previous data is found" in {
See comment below.

2024-03-12 10:00 UTC, aashik-varahan commented on test/controllers/rfm/NfmRegisteredAddressControllerSpec.scala
> +            ("addressLine1", "27 house"),
@jassalrichy - Updated the test case to setup  rfmNfmRegisteredAddressPage with a valid address to test the scenario.

2024-03-12 10:00 UTC, aashik-varahan commented on test/controllers/rfm/NfmRegisteredAddressControllerSpec.scala
>      "must redirect to the UnderConstructionController page when valid data is submitted" in {
This is already satisfied as part of the below test case:
**"redirect to JourneyRecoveryController if previous page not answered"**

2024-03-19 17:18 UTC, alikouhestani requested changes

2024-03-19 17:18 UTC, alikouhestani commented on app/controllers/rfm/NoIdNameRegistrationController.scala
> +class NoIdNameRegistrationController @Inject() (
why does the controller not have the prefix "rfm"? Also we generally don't use "no id" in any of our controllers so could you please change this to "RfmNameRegistrationController" (same with the page name etc) to remain consistent with the rest of the classes

2024-03-19 17:18 UTC, alikouhestani commented on app/controllers/rfm/NoIdNameRegistrationController.scala
> +          } yield Redirect(controllers.rfm.routes.NoIdRegisteredAddressController.onPageLoad())
Please can you merge the recent changes from main into your branch and use the Navigator pattern (similar to the rest of the classes) let me know if you want to pair up on this

2024-03-19 17:18 UTC, alikouhestani commented on app/controllers/rfm/NoIdRegisteredAddressController.scala
> +class NoIdRegisteredAddressController @Inject() (
Again can you please add the "Rfm" prefix and name this to something like "RfmRegisteredAddressController" to remain consistent

2024-03-19 17:18 UTC, alikouhestani commented on app/controllers/rfm/NoIdRegisteredAddressController.scala
> +          val preparedForm = request.userAnswers.get(RfmNoIdRegisteredAddressPage) match {
Same here with the page

2024-03-19 17:18 UTC, alikouhestani commented on app/controllers/rfm/NoIdRegisteredAddressController.scala
> +              } yield Redirect(controllers.routes.UnderConstructionController.onPageLoad)
Please use the Navigator pattern here

2024-03-19 17:18 UTC, alikouhestani commented on app/forms/RfmNoIdNameRegistrationFormProvider.scala
> +class RfmNoIdNameRegistrationFormProvider @Inject() extends Mappings {
Same with the naming convention here

2024-03-19 17:18 UTC, alikouhestani commented on app/mapping/Constants.scala
> +  final val MAX_LENGTH_35   = 35
Can you please name this something related to address fields? i.e. ADDRESS_MAX_LENGTH or something

2024-03-19 17:18 UTC, alikouhestani commented on app/pages/RfmNoIdRegisteredAddressPage.scala
> +  override def toString: String = "rfmNfmRegisteredAddress"
rename "rfmNfmRegisteredAdddress" to something more appropriate once you have decided on a better name for this page (we currently use [prefix]RegisteredAddress so I suggest adhering to that to remain consistent

2024-03-19 17:18 UTC, alikouhestani commented on test/controllers/rfm/NfmNameRegistrationControllerSpec.scala
> +class NfmNameRegistrationControllerSpec extends SpecBase {
Your classes and spec files must have the same name with only a "spec" at the end that is different. This name is currently not connected to any other Scala classes

2024-03-19 17:18 UTC, alikouhestani commented on test/controllers/rfm/NfmNameRegistrationControllerSpec.scala
> +
Once you rewrite your controllers to use navigator pattern, you'd need to test any routes in that navigator's spec file and not in the controller

2024-03-19 17:18 UTC, alikouhestani commented on test/controllers/rfm/NfmRegisteredAddressControllerSpec.scala
> +/*
Again, this spec file needs to be renamed to match the controller class

2024-03-19 17:18 UTC, alikouhestani commented on test/controllers/rfm/NfmRegisteredAddressControllerSpec.scala
> +    "must return OK and the correct view for a GET if RFM access is enabled and no previous data is found" in {
Same applies to this controller spec. It needs to match its controller

2024-03-19 17:18 UTC, alikouhestani commented on test/controllers/rfm/NfmRegisteredAddressControllerSpec.scala
> +        status(result) mustEqual OK
test says "must return OK and the correct view " but you are not testing any view here you are just testing the status

2024-03-21 17:38 UTC, MarjanMubarok commented on app/views/rfm/RfmNameRegistrationView.scala.html
> +        @sectionHeader(messages("rfm.registration.heading.caption"))
Move line 41 so it is between layout and formhelper otherwise it will cause an accessibilty issue.

2024-03-21 17:38 UTC, MarjanMubarok commented on app/views/rfm/RfmRegisteredAddressView.scala.html
> +@sectionHeader(messages("rfm.registration.heading.caption"))
Move line 41 so it is between layout and formhelper otherwise it will cause an accessibilty issue.

2024-03-21 17:43 UTC, MarjanMubarok commented on app/views/rfm/RfmRegisteredAddressView.scala.html
> +<h1 class="govuk-heading-l long-word">@messages("rfm.registeredAddress.heading", UserName)</h1>
Is there a component for this in views.html.components.gds? If so use it. If not you could make it.

2024-03-25 09:10 UTC, aashik-varahan commented
@jassalrichy @alikouhestani - Resolved the PR comments, please re-review now.

2024-03-25 10:17 UTC, alikouhestani requested changes

2024-03-25 10:20 UTC, aashik-varahan commented on app/controllers/rfm/NoIdCheckYourAnswersController.scala
> +class NoIdCheckYourAnswersController @Inject() (
@alikouhestani - This is part of PIL-740, can you please comment there. It's merged with PIL-739

2024-03-25 10:20 UTC, aashik-varahan commented on app/pages/RfmCheckYourAnswersLogicPage.scala
> +
Same Here

2024-03-25 10:23 UTC, aashik-varahan commented on app/viewmodels/checkAnswers/RfmRegisteredAddressSummary.scala
> +            .withVisuallyHiddenText(messages("rfm.registeredAddress.change.hidden"))
@alikouhestani - This is part of PIL-740, can you please comment there. It's merged with PIL-739. @jassalrichy Can you please check this comment?

2024-03-25 10:50 UTC, aashik-varahan commented on conf/messages.en
> +rfm.registeredAddress.change.hidden =  the registered office address of the nominated filing member
Same here

2024-03-25 13:13 UTC, aashik-varahan commented on test/controllers/rfm/RfmRegisteredAddressControllerSpec.scala
> +    "redirect to JourneyRecoveryController if previous page not answered OnSubmit" in {
Changed to POST method onSubmit

2024-03-27 09:46 UTC, alikouhestani submitted a review, later dismissed

2024-04-04 08:20 UTC, AKKUM approved these changes

2024-04-04 08:26 UTC, merged