[PIL-740] CYA - NFM No ID flow
hmrc/pillar2-frontend pull request #227
Opened 2024-03-11 16:55 UTC by jassalrichy

Branch PIL-739 has been merged into this branch.

2024-03-25 14:52 UTC, alikouhestani requested changes

2024-03-25 14:52 UTC, alikouhestani commented on app/controllers/rfm/NoIdNameRegistrationController.scala
> +class NoIdNameRegistrationController @Inject() (
The prefix "noID" is never used in any class name as we usually use the journey's prefix i.e. "Rfm". Can you please rename to "RfmNameRegistrationController" to follow the usual naming convention. Same for spec file

2024-03-25 14:52 UTC, alikouhestani commented on app/controllers/rfm/NoIdRegisteredAddressController.scala
> +class NoIdRegisteredAddressController @Inject() (
Again, could you please rename to "RfmRegisteredAddress"

2024-03-25 14:52 UTC, alikouhestani commented on app/controllers/rfm/NoIdRegisteredAddressController.scala
> +          val preparedForm = request.userAnswers.get(RfmNoIdRegisteredAddressPage) match {
Again, I would personally remove the "NoID" from the name here and just change to "RfmRegisteredAddressPage" to follow the usual pattern used in other journeys

2024-03-25 14:52 UTC, alikouhestani commented on app/navigation/ReplaceFilingMemberNavigator.scala
> +  private def whichCheckYourAnswerPageSecurityQuestions(userAnswers: UserAnswers): Call =
Whilst something similar might be needed later on to decide the routing for the submit and review or the other CYA page, this is currently redundant and not correct as the following CYA pages don't display any two same fields.

2024-03-25 14:52 UTC, alikouhestani commented on app/navigation/ReplaceFilingMemberNavigator.scala
> +  private def whichCheckYourAnswerPageNoIdQuestions(userAnswers: UserAnswers): Call =
same as above

2024-03-25 14:52 UTC, alikouhestani commented on app/pages/RfmNoIdNameRegistrationPage.scala
> +  override def toString: String = "rfmNfmNameRegistration"
remove the "Nfm" from the name "rfmNfmNameRegistration"

2024-03-25 14:52 UTC, alikouhestani commented on app/pages/RfmNoIdRegisteredAddressPage.scala
> +  override def toString: String = "rfmNfmRegisteredAddress"
Same as above, remove"Nfm"

2024-03-25 14:52 UTC, alikouhestani commented on conf/messages.en
> +rfm.noIdRegisteredAddress.change.hidden =  the registered office address of the nominated filing member
You have two values set against rfm.noIdRegisteredAddress.change.hidden
remove one

2024-03-25 14:52 UTC, alikouhestani commented on test/controllers/rfm/NoIdCheckYourAnswersControllerSpec.scala
> +      val testConfig = Configuration("features.rfmAccessEnabled" -> true)
This toggle is already set to true in the local environment so this is redundant

2024-03-25 14:52 UTC, alikouhestani commented on test/controllers/rfm/NoIdCheckYourAnswersControllerSpec.scala
> +      val testConfig = Configuration("features.rfmAccessEnabled" -> true)
same here

2024-03-25 14:52 UTC, alikouhestani commented on test/controllers/rfm/NoIdRegisteredAddressControllerSpec.scala
> +        status(result) mustEqual BAD_REQUEST
could ensure the content of the view here too

2024-03-26 10:09 UTC, jassalrichy commented on app/controllers/rfm/NoIdNameRegistrationController.scala
> +class NoIdNameRegistrationController @Inject() (
Completed by @aashik-varahan in branch PIL-739

2024-03-26 10:09 UTC, jassalrichy commented on app/controllers/rfm/NoIdRegisteredAddressController.scala
> +class NoIdRegisteredAddressController @Inject() (
Completed by @aashik-varahan in branch PIL-739

2024-03-26 10:09 UTC, jassalrichy commented on app/controllers/rfm/NoIdRegisteredAddressController.scala
> +          val preparedForm = request.userAnswers.get(RfmNoIdRegisteredAddressPage) match {
Completed by @aashik-varahan in branch PIL-739

2024-03-26 10:10 UTC, jassalrichy commented on app/pages/RfmNoIdRegisteredAddressPage.scala
> +  override def toString: String = "rfmNfmRegisteredAddress"
Completed by @aashik-varahan in branch PIL-739

2024-03-26 10:20 UTC, jassalrichy commented on test/controllers/rfm/NoIdCheckYourAnswersControllerSpec.scala
> +      val testConfig = Configuration("features.rfmAccessEnabled" -> true)
Done

2024-03-26 10:32 UTC, jassalrichy commented on test/controllers/rfm/NoIdCheckYourAnswersControllerSpec.scala
> +      val testConfig = Configuration("features.rfmAccessEnabled" -> true)
Done

2024-03-26 14:10 UTC, jassalrichy commented on app/pages/RfmNoIdNameRegistrationPage.scala
> +  override def toString: String = "rfmNfmNameRegistration"
Completed by @aashik-varahan in branch PIL-739

2024-03-26 14:45 UTC, jassalrichy commented on conf/messages.en
> +rfm.noIdRegisteredAddress.change.hidden =  the registered office address of the nominated filing member
Done

2024-03-26 15:06 UTC, jassalrichy commented on app/navigation/ReplaceFilingMemberNavigator.scala
> +  private def whichCheckYourAnswerPageNoIdQuestions(userAnswers: UserAnswers): Call =
For RfmRegisteredAddress & RfmNameRegistration, the final review and submit CYA page can contain the same two fields. See Mural fig. PIL-767 16.3a
Have updated navigation to redirect to UnderContrustion page, until this page is develeoped.

2024-03-26 15:07 UTC, jassalrichy commented on app/navigation/ReplaceFilingMemberNavigator.scala
> +  private def whichCheckYourAnswerPageSecurityQuestions(userAnswers: UserAnswers): Call =
Done.

2024-03-26 16:19 UTC, aashik-varahan commented on test/controllers/rfm/NoIdRegisteredAddressControllerSpec.scala
> +        status(result) mustEqual BAD_REQUEST
@alikouhestani @jassalrichy - Added Content view to the unit test

2024-03-27 09:34 UTC, alikouhestani approved these changes

2024-04-04 08:26 UTC, merged