[PIL-306][AB]:Updated task list tags
hmrc/pillar2-frontend pull request #59
Opened 2023-06-29 14:49 UTC by alexbrook3

2023-06-30 11:06 UTC, AKKUM submitted a review, later dismissed

2023-07-07 10:48 UTC, javed-iqbal1 submitted a review, later dismissed

2023-07-17 06:57 UTC, AKKUM commented
Please remove conflict and also looking at a lot of other brach code is there please branch from main reflect your changes. Feel free to discuss.

2023-07-17 06:58 UTC, AKKUM requested changes
Please remove conflict and also looking at a lot of other brach code is there please branch from main reflect your changes. Feel free to discuss.

2023-07-17 10:51 UTC, closed without merging