PIL-284 Changes to eligibility questions
hmrc/pillar2-frontend pull request #66
Opened 2023-07-12 13:49 UTC by javed-iqbal1

2023-07-12 16:16 UTC, AKKUM commented on app/controllers/eligibility/RegisteringNFMGroupController.scala
> +            case "yes" =>
Can we get yes no from class?

2023-07-12 16:17 UTC, AKKUM commented on app/models/GroupTerritories.scala
> +  case object None extends WithName("none") with RegisteringTheUPGroup
Why do we need None?

2023-07-12 16:24 UTC, AKKUM commented on app/views/RegisteringNFMGroupView.scala.html
> +        <span class="govuk-caption-l">@messages("registeringNFMGroup.caption")</span>
message in camel case would be good

2023-07-13 12:01 UTC, javed-iqbal1 commented on app/models/GroupTerritories.scala
> +  case object None extends WithName("none") with RegisteringTheUPGroup
removed

2023-07-13 12:01 UTC, javed-iqbal1 commented on app/views/RegisteringNFMGroupView.scala.html
> +        <span class="govuk-caption-l">@messages("registeringNFMGroup.caption")</span>
made camel cases

2023-07-14 17:05 UTC, AKKUM commented on app/controllers/eligibility/RegisteringTheUPGroupController.scala
>              case "no" =>
Could we case matching with class rather than string as previously done in same pull request. eg app/controllers/eligibility/RegisteringNFMGroupController.scala

2023-07-14 17:07 UTC, AKKUM commented on app/controllers/fmRegistration/IsNFMUKBasedController.scala
> +}
Why do need this class mixed with eligibility question? is this a part of ticket scope?

2023-07-14 17:54 UTC, AKKUM commented on app/forms/IsNFMUKBasedFormProvider.scala
> +}
same here, is this required?

2023-07-14 17:56 UTC, AKKUM commented on app/views/RegisteringNFMGroupView.scala.html
> +                legend = LegendViewModel(messages("registeringNfmGroup.heading")).asPageHeading().withCssClass("govuk-label--l"),
do we need to pass cssclass? use font size.

2023-07-14 17:56 UTC, AKKUM commented on app/views/TurnOverEligibilityView.scala.html
> +                legend = LegendViewModel(messages("turnOverEligibility.heading")).asPageHeading().withCssClass("govuk-label--l"),
same here

2023-07-14 18:00 UTC, AKKUM commented on test/controllers/eligibility/RegisteringNFMGroupControllerSpec.scala
> +}
could we do unit test with application builder.

2023-07-17 07:02 UTC, AKKUM requested changes
Please look at the comments. Happy to discuss if required.

2023-07-17 08:50 UTC, closed without merging