Pil 299-Task 2: enter NFM's contact name and email address (no ID flow)
hmrc/pillar2-frontend pull request #68
Opened 2023-07-14 16:07 UTC by nitin-srivastav

2023-07-17 07:04 UTC, AKKUM requested changes
Please remove the conflicts and also work with the new structure what team has decided to maintain database structure. Happy to discuss.

2023-08-02 13:27 UTC, Al-kouhestani requested changes

2023-08-02 13:27 UTC, Al-kouhestani commented on app/controllers/fm/NfmContactNameController.scala
> +                      withoutIdRegData = Some(WithoutIdNfmData(fmContactName = Some(value), registeredFmName = getUserName(request)))
will the user's previous input be saved here if they return to this page? i'm not sure they would. Happy to have a chat

2023-08-02 13:27 UTC, Al-kouhestani commented on app/models/registration/WithoutIdRegData.scala
> +  nFMEmailAddress:       Option[String] = None,
This is the wrong design. This is registration data whereas your ticket is for the filing member journey. you shouldn't need to add anything here. Happy to have a chat

2023-08-02 13:27 UTC, Al-kouhestani commented on app/views/fmview/NfmContactNameView.scala.html
> +                field = form("fmContactName"),
you need to change this to value here instead of "fmContactName"

2023-08-02 13:27 UTC, Al-kouhestani commented on generated-test/controllers/NFMEmailAddressControllerSpec.scala
> +  def controller(): NFMEmailAddressController =
do we need this controller method? it is not used anywhere

2023-08-02 13:27 UTC, Al-kouhestani commented on migrations/NFMEmailAddress.sh
> +echo "Adding routes to conf/app.routes"
what is this file?

2023-08-02 13:27 UTC, Al-kouhestani commented on migrations/NFMEmailAddress.sh
> +echo "Adding routes to conf/app.routes"
Do we need this? what is it doing?

2023-08-02 13:27 UTC, Al-kouhestani commented on test/controllers/fm/NfmContactNameControllerSpec.scala
> +  def controller(): NfmContactNameController =
Again, do we need this controller? it is not used anywhere

2023-08-02 13:27 UTC, Al-kouhestani commented on test/controllers/fm/NfmEmailAddressControllerSpec.scala
> +  val formProvider = new NfmEmailAddressFormProvider()
Why do we have two instances of the same thing here?

2023-08-02 15:14 UTC, nitin-srivastav commented on app/views/fmview/NfmContactNameView.scala.html
> +                field = form("fmContactName"),
This is not mandatory though, in fact I prefer "fmContactName" over "value" to as it makes more sense in terms of readability but yes if we want to support scaffold then "value" is fine.

2023-08-02 15:42 UTC, AKKUM commented on app/controllers/fm/NfmContactNameController.scala
> +}
Is the bookmarking issue fixed? if user directly hit the url what happens?

2023-08-02 15:42 UTC, AKKUM commented on app/controllers/fm/NfmEmailAddressController.scala
> +}
Same bookmark issue here.

2023-08-02 15:43 UTC, AKKUM commented on app/forms/NfmContactNameFormProvider.scala
> +      "value" -> text("nFMContactName.error.required")
camel case fix pls. nFMContactName

2023-08-02 15:44 UTC, AKKUM commented on app/forms/NfmEmailAddressFormProvider.scala
> +      "value" -> text("nFMEmailAddress.error.required", Seq(userName))
Same came case here.

2023-08-02 15:47 UTC, AKKUM commented on test/controllers/testdata/Pillar2TestData.scala
> +    withoutIdRegData = Some(
Can we get the data pillar2 test data.

2023-08-03 09:14 UTC, AKKUM commented on conf/messages.en
> +nFMEmailAddress.change.hidden = nFMEmailAddress
Camel case here.

2023-08-07 13:32 UTC, Al-kouhestani requested changes

2023-08-07 13:32 UTC, Al-kouhestani commented on app/controllers/fm/NfmEmailAddressController.scala
> +                            fmContactName = Some(getUserName(request))
Both registererdFmName and fmContactName are filled with the same value, this is not correct.

2023-08-07 13:35 UTC, nitin-srivastav commented on app/controllers/fm/NfmEmailAddressController.scala
> +                            fmContactName = Some(getUserName(request))
Right, this will be corrected once we have previous page is in place which is still not in main.

2023-08-14 08:24 UTC, javed-iqbal1 approved these changes

2023-08-14 09:47 UTC, AKKUM approved these changes

2023-08-14 09:49 UTC, merged