PIL-168:Task 3: enter group's accounting period
hmrc/pillar2-frontend pull request #90
Opened 2023-09-08 16:34 UTC by nitin-srivastav

2023-09-08 16:44 UTC, Al-kouhestani requested changes

2023-09-08 16:44 UTC, Al-kouhestani commented on app/controllers/subscription/MneOrDomesticController.scala
> +                      primaryContactName = subscriptionData.primaryContactName,
We don't need all these values, they are defaulted to none so you really only need to enter a value for those fields needed i.e. domesticorMne and status. I am not sure why you have edited this controller

2023-09-08 16:44 UTC, Al-kouhestani commented on app/viewmodels/checkAnswers/GroupAccountingPeriodSummary.scala
> +            .withVisuallyHiddenText(messages("groupAccountingPeriod.change.hidden"))
This is not the right hidden message

2023-09-08 16:44 UTC, Al-kouhestani commented on test/controllers/GroupAccountingPeriodControllerSpec.scala
> +
Please add an additional unit test for remapFormErrors method in the controller

2023-09-11 15:46 UTC, closed without merging

2023-09-11 15:47 UTC, nitin-srivastav commented
The changes have been merged with another PR PIL-168-Al